[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
