[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
